version: '3.3'

services:
   myredis:
     image: redis
     restart: always
     #ports:
     #  - "6379:6379"
   pythonclient:
    depends_on:
      - myredis
    image: python-redis
    restart: "no"
    volumes:
      - ./python_dir/:/scripts/
   web:
     depends_on:
       - myredis
     image: php-redis
     ports:
       - "8080:80"
     restart: always
     volumes:
             - ./php_dir/:/var/www/html/
