version: "3.3"


services:
        myredis:
                image: "redis"
                restart : "always"
        web:
                image : "nginx"
                ports:
                        - 8084:80
                volumes:
                        - ./html:/var/www/html/
                
